### ISSUE TITLE
Поддержка вариативности фраз

### ISSUE THREAD

**Issue by abelozerov** [dshved/fridaybot#127]
В текущий версии для запуска команд необходимо написать четкую фразу, например "выпускайте гуся".

Хотелось бы, чтобы например такие фразы как "выпускай гуся", "выпустите гуся", "гуся выпускайте", "выпускайте уже гуся" и другое незарардкоденное множество фраз, также поддерживались и приводили к выпуску гуся. Гусь как пример, хотелось бы видеть такое для всех команд

Могу заняться этим.
Планирую реализовать через эту библиотеку: https://github.com/NaturalNode/natural#stemmers

**Comment by dshved** [comment]
Четкая команда дает больше гарантий, что не будет ложного срабатывания. Если сделать так, что бот будет вырывать слова из контекста и как-то на них реагировать, это может привести к непредсказуемым результатам. Тем более что чат, в котором он работает в первую очередь для общения, а не для взаимодействия с ботом.

**Comment by abelozerov** [comment]
Да, твоя позиция понятна. Могу предложить сделать достаточно жесткий вариант: токенизировать слова и запускать команду, только если все нужные токены присутствуют в фразе и не присутствуют никакие другие токены

**Comment by dshved** [comment]
Можешь попробовать. Интересно посмотреть, что из этого выйдет. Напиши мне в личку, я дам доступ в чат, где можно будет тестировать бота.
